// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd945bz_i7BUWGklMqFhaRxEeTTiey8Jw',
    appId: '1:114248023929:web:0964c4a561591fde06b9a8',
    messagingSenderId: '114248023929',
    projectId: 'first-flutter-app-007',
    authDomain: 'first-flutter-app-007.firebaseapp.com',
    storageBucket: 'first-flutter-app-007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVl9KHtdB8g7YRqkuwso8v12snixWeOpg',
    appId: '1:114248023929:ios:89a8091a175ab3e606b9a8',
    messagingSenderId: '114248023929',
    projectId: 'first-flutter-app-007',
    storageBucket: 'first-flutter-app-007.appspot.com',
    iosClientId: '114248023929-6h7u1i78q0ja0stip67i88ag1el5ajbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVl9KHtdB8g7YRqkuwso8v12snixWeOpg',
    appId: '1:114248023929:ios:89a8091a175ab3e606b9a8',
    messagingSenderId: '114248023929',
    projectId: 'first-flutter-app-007',
    storageBucket: 'first-flutter-app-007.appspot.com',
    iosClientId: '114248023929-6h7u1i78q0ja0stip67i88ag1el5ajbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
